Friend Module MOD_CONST

#Region "config関連"
    Public Const cstCONFIG_HOT_KEY_INDEX_CAPT_ONE As String = "HOT_KEY_INDEX_CAPT_ONE"
    Public Const cstCONFIG_HOT_KEY_INDEX_CAPT As String = "HOT_KEY_INDEX_CAPT"
    Public Const cstCONFIG_HOT_KEY_INDEX_OVERLAY As String = "HOT_KEY_INDEX_OVERLAY"
    Public Const cstCONFIG_HOT_KEY_INDEX_ROTATE As String = "HOT_KEY_INDEX_ROTATE"
    Public Const cstCONFIG_USE_JOYSTICK As String = "USE_JOYSTICK"
    Public Const cstCONFIG_USE_JOYSTICK_BUTTON_SCRLK As String = "USE_JOYSTICK_BUTTON_SCRLK"
    Public Const cstCONFIG_USE_JOYSTICK_BUTTON_CAPT_ONE As String = "USE_JOYSTICK_BUTTON_CAPT_ONE"
    Public Const cstCONFIG_USE_JOYSTICK_BUTTON_CAPT As String = "USE_JOYSTICK_BUTTON_CAPT"
    Public Const cstCONFIG_USE_JOYSTICK_BUTTON_OVERLAY As String = "USE_JOYSTICK_BUTTON_OVERLAY"
    Public Const cstCONFIG_USE_JOYSTICK_BUTTON_ROTATE As String = "USE_JOYSTICK_BUTTON_ROTATE"

    Public Const cstCONFIG_PATH_SAVE As String = "PATH_SAVE"
    Public Const cstCONFIG_PATH_SAVE_FOLDER_NAME As String = "PATH_SAVE_FOLDER_NAME"
    Public Const cstCONFIG_PATH_SAVE_FILE_NAME As String = "PATH_SAVE_FILE_NAME"
    Public Const cstCONFIG_IMAGE_FORMAT As String = "IMAGE_FORMAT"
    Public Const cstCONFIG_ADD_COPYRIGHT As String = "ADD_COPYRIGHT"
    Public Const cstCONFIG_IMAGE_INDEX As String = "IMAGE_INDEX"
    Public Const cstCONFIG_SOUND_CAPTURE As String = "SOUND_CAPTURE"
    Public Const cstCONFIG_COUNT_CAPTURE As String = "COUNT_CAPTURE"
    Public Const cstCONFIG_TIMER_CAPTURE As String = "TIMER_CAPTURE"
    Public Const cstCONFIG_INTERVAL_CAPTURE As String = "INTERVAL_CAPTURE"
    Public Const cstCONFIG_SEND_KEY_INDEX As String = "SEND_KEY_INDEX"
    Public Const cstCONFIG_INTERVAL_SEND_KEY As String = "INTERVAL_SEND_KEY"

    Public Const cstCONFIG_OVERLAY_SHORTCUT As String = "OVERLAY_SHORTCUT"
    Public Const cstCONFIG_OVERLAY_COMPOSITION As String = "OVERLAY_COMPOSITION"
    Public Const cstCONFIG_OVERLAY_CAPT_PARAM As String = "OVERLAY_CAPT_PARAM"
    Public Const cstCONFIG_OVERLAY_HISTOGRAM As String = "OVERLAY_HISTOGRAM"
    Public Const cstCONFIG_OVERLAY_THUMBNAIL As String = "OVERLAY_THUMBNAIL"
    Public Const cstCONFIG_OVERLAY_SHORTCUT_ALIGNMENT As String = "OVERLAY_SHORTCUT_ALIGNMENT"
    Public Const cstCONFIG_OVERLAY_CAPT_PARAM_ALIGNMENT As String = "OVERLAY_CAPT_PARAM_ALIGNMENT"
    Public Const cstCONFIG_OVERLAY_HISTOGRAM_ALIGNMENT As String = "OVERLAY_HISTOGRAM_ALIGNMENT"
    Public Const cstCONFIG_OVERLAY_THUMBNAIL_ALIGNMENT As String = "OVERLAY_THUMBNAIL_ALIGNMENT"
    Public Const cstCONFIG_OVERLAY_COMPOSITION_TYPE As String = "OVERLAY_COMPOSITION_TYPE"

    Public Const cstCONFIG_ROTATE_POSITION_X As String = "ROTATE_POSITION_X"
    Public Const cstCONFIG_ROTATE_POSITION_Y As String = "ROTATE_POSITION_Y"
    Public Const cstCONFIG_ROTATE_SIZE_W As String = "ROTATE_SIZE_W"
    Public Const cstCONFIG_ROTATE_SIZE_H As String = "ROTATE_SIZE_H"

    Public Const cstCONFIG_LIGHT_ROTATE_LR_KEY As String = "LIGHT_ROTATE_LR_KEY"
    Public Const cstCONFIG_LIGHT_ROTATE_LR_MS As String = "LIGHT_ROTATE_LR_MS"
    Public Const cstCONFIG_LIGHT_DISTANCE_KEY As String = "LIGHT_DISTANCE_KEY"
    Public Const cstCONFIG_LIGHT_DISTANCE_MS As String = "LIGHT_DISTANCE_MS"
    Public Const cstCONFIG_LIGHT_ROTATE_UD_KEY As String = "LIGHT_ROTATE_UD_KEY"
    Public Const cstCONFIG_LIGHT_ROTATE_UD_MS As String = "LIGHT_ROTATE_UD_MS"
#End Region

#Region "回転イメージ"
    Public Const cstROTATE_SIZE_W_DEFAULT As Integer = 540
    Public Const cstROTATE_SIZE_H_DEFAULT As Integer = 960
#End Region

End Module
